import type { ImgHTMLAttributes } from 'react'

interface ImageProps extends ImgHTMLAttributes<HTMLImageElement> {
  /** Path to the source image (e.g. "/images/foo.png"). A WebP variant is
   *  derived by swapping the extension and must exist on disk (generated by
   *  `yarn optimize:media`). Non-raster sources (e.g. SVG) are used as-is. */
  src: string
  alt: string
  /** Above-the-fold media: load eagerly with high fetch priority. */
  priority?: boolean
}

const RASTER = /\.(png|jpe?g)$/i

/**
 * Renders a single optimized `<img>` with lazy loading and async decoding by
 * default. Raster sources are swapped to their `.webp` variant. We deliberately
 * avoid a `<picture>` wrapper: `display: contents` breaks `object-fit`,
 * percentage heights and centering through the wrapper in WebKit/Safari, so a
 * bare `<img>` is used to keep layout behaviour identical to a plain image.
 */
export default function Image({ src, alt, priority = false, ...imgProps }: ImageProps) {
  const optimized = src.replace(RASTER, '.webp')

  return (
    <img
      src={optimized}
      alt={alt}
      loading={priority ? 'eager' : 'lazy'}
      decoding="async"
      fetchPriority={priority ? 'high' : 'auto'}
      {...imgProps}
    />
  )
}
