import { useEffect, useRef, useState, type VideoHTMLAttributes } from 'react'

interface LazyVideoProps
  extends Omit<VideoHTMLAttributes<HTMLVideoElement>, 'src' | 'poster' | 'autoPlay'> {
  /** Path to the MP4 (e.g. "/images/foo.mp4"). The WebM and WebP poster are
   *  derived by swapping the extension and must exist on disk (generated by
   *  `yarn optimize:media`). */
  src: string
  /** Override the derived poster path if needed. */
  poster?: string
}

/**
 * A muted, looping, inline video that defers downloading until it nears the
 * viewport, then plays while visible and pauses when scrolled away. This stops
 * a page full of autoplay videos from downloading all at once — a major win on
 * iOS where every visible `<video autoplay>` otherwise fetches immediately.
 */
export default function LazyVideo({ src, poster, className, ...rest }: LazyVideoProps) {
  const ref = useRef<HTMLVideoElement>(null)
  const [active, setActive] = useState(false)

  const webm = src.replace(/\.mp4$/i, '.webm')
  const posterSrc = poster ?? src.replace(/\.mp4$/i, '-poster.webp')

  useEffect(() => {
    const el = ref.current
    if (!el) return

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setActive(true)
          el.play?.().catch(() => {})
        } else {
          el.pause?.()
        }
      },
      { rootMargin: '200px 0px', threshold: 0.1 },
    )

    observer.observe(el)
    return () => observer.disconnect()
  }, [])

  // Once sources are attached, load and start playback.
  useEffect(() => {
    const el = ref.current
    if (!active || !el) return
    el.load()
    el.play().catch(() => {})
  }, [active])

  return (
    <video
      ref={ref}
      className={className}
      poster={posterSrc}
      muted
      loop
      playsInline
      preload="none"
      {...rest}
    >
      {active && (
        <>
          <source src={webm} type="video/webm" />
          <source src={src} type="video/mp4" />
        </>
      )}
    </video>
  )
}
